-- MySQL Script generated by MySQL Workbench
-- Tue Mar 12 06:28:38 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema CSoT
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema CSoT
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `CSoT` DEFAULT CHARACTER SET utf8 ;
USE `CSoT` ;

-- -----------------------------------------------------
-- Table `CSoT`.`employee`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CSoT`.`employee` (
  `id_employee` INT NOT NULL AUTO_INCREMENT,
  `firstname` VARCHAR(50) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `fathername` VARCHAR(45) NOT NULL,
  `date_of_born` DATE NOT NULL,
  `job` VARCHAR(45) NOT NULL,
  `contact` VARCHAR(9) NOT NULL,
  PRIMARY KEY (`id_employee`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CSoT`.`autorization`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CSoT`.`autorization` (
  `id_autorization` INT NOT NULL AUTO_INCREMENT,
  `id_employee` INT NULL,
  `login` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_autorization`),
  INDEX `employee_idx` (`id_employee` ASC) VISIBLE,
  CONSTRAINT `employee`
    FOREIGN KEY (`id_employee`)
    REFERENCES `CSoT`.`employee` (`id_employee`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CSoT`.`ServiceTE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CSoT`.`ServiceTE` (
  `id_report` INT NOT NULL AUTO_INCREMENT,
  `date_of_service` DATE NOT NULL,
  `id_employee` INT NOT NULL,
  `id_technique` INT NOT NULL,
  `amount_of_faults` INT NOT NULL,
  `employee_id_employee` INT NOT NULL,
  `TE_id_technique` INT NOT NULL,
  PRIMARY KEY (`id_report`, `employee_id_employee`, `TE_id_technique`, `date_of_service`),
  INDEX `employee_idx` (`id_employee` ASC) VISIBLE,
  INDEX `te_idx` (`id_technique` ASC) VISIBLE,
  CONSTRAINT `employee`
    FOREIGN KEY (`id_employee`)
    REFERENCES `CSoT`.`employee` (`id_employee`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `te`
    FOREIGN KEY (`id_technique`)
    REFERENCES `CSoT`.`TE` (`id_technique`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CSoT`.`TypeTE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CSoT`.`TypeTE` (
  `id_type` INT NOT NULL AUTO_INCREMENT,
  `name_of_type` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_type`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CSoT`.`TE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CSoT`.`TE` (
  `id_technique` INT NOT NULL AUTO_INCREMENT,
  `name_of_technique` VARCHAR(45) NOT NULL,
  `manufacturer` VARCHAR(45) NOT NULL,
  `id_type` INT NOT NULL,
  `date_of_service` DATE NOT NULL,
  PRIMARY KEY (`id_technique`),
  INDEX `service_idx` (`date_of_service` ASC) VISIBLE,
  INDEX `type_idx` (`id_type` ASC) VISIBLE,
  CONSTRAINT `service`
    FOREIGN KEY (`date_of_service`)
    REFERENCES `CSoT`.`ServiceTE` (`date_of_service`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `type`
    FOREIGN KEY (`id_type`)
    REFERENCES `CSoT`.`TypeTE` (`id_type`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
